server:
  port: 8899
spring:
  datasource:
    url: jdbc:mysql://192.168.1.6:3306/schoolsys?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: deng123
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 300
      initial-size: 20
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 10
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1
  redis:
    database: 5
    host: 192.168.1.6
    password:
    port: 6379
    timeout: 3000
    pool:
      max-idle: 500
      min-idle: 50
      max-active: 2000
      max-wait: 1000
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  jackson:
    serialization:
      indent_output: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect






  devtools:
    restart:
      enabled: false
      #  security:
#    filter:
#      order: 5
logging:
  config: classpath:log4j2.xml

database:
  pagefix: offset


## JWT
# header:凭证(校验的变量名), expire:有效期7天(单位:s), secret:秘钥(普通字符串)  86400一天   604800一个星期
app:
  jwt:
    header: token
    expire: 604800
    secret: aHR0cHM6Ly9teS5vc2NoaW5hLm5ldC91LzM2ODE4Njg=
  sysconfig:
    sessionExpire: 86400
